name: Frontend Deploy (Next.js)

on:
    workflow_run:
        workflows: [CI]
        types: [completed]

jobs: 
    deploy_staging:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.conclusion == 'staging'
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Render (staging)
              env: 
                RENDER_DEPLOY_HOOK_URL_STAGING: ${{ secrets.RENDER_DEPLOY_HOOK_URL_STAGING }}
              run: curl -fsSL "$RENDER_DEPLOY_HOOK_URL_STAGING"