name: Backend CI

on:
    push:
        branches: [main, staging]
    pull_request: {}

concurrency:
    group: backend-${{ github.ref }}
    cancel-in-progress: false

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:17
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U postgres"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              working-directory: ./backend
              run: |
                  python -m pip install --upgrade pip
                  pip install --no-cache-dir -r requirements.txt

            - name: Run migrations
              working-directory: ./backend
              env:
                  DEBUG: "True"
                  SECRET_KEY: "test-secret"
                  ALLOWED_HOSTS: "localhost,127.0.0.1"
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
              run: |
                  python manage.py migrate --noinput

            - name: Run tests
              working-directory: ./backend
              env:
                  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
              run: |
                  python manage.py test --noinput
